name: "2.Build beta version"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["1.Build latest version"]
    branches: [main]
    types:
      - completed

jobs:
  build-latest-images:
    runs-on: ubuntu-latest
    name: "Build beta version"
    env:
      TAG: beta
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_REPO: ${{ secrets.DOCKER_REPO }}

    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Check and Rebuild
        run: |
          [ -e README.md ] && NOW=$(awk '/${{ env.TAG }}/{print $NF}' README.md)
          LATEST=$(sudo wget -qO- "https://api.github.com/repos/SagerNet/sing-box/releases" | awk -F '["v]' '/tag_name.*${{ env.TAG }}/{print $5;exit}')
          echo "Now: $NOW"
          echo "Latest: $LATEST"
          if [ "$NOW" != "$LATEST" ]; then
            sed -i "s/\(${{ env.TAG }}:\).*/\1 $LATEST/" README.md
            echo "VERSION=$LATEST" >> $GITHUB_ENV
            echo "DATE=$(date "+%Y/%m/%d")" >> $GITHUB_ENV
            echo "ARCH=$(uname -m | sed "s#x86_64#amd64#; s#aarch64#arm64#")" >> $GITHUB_ENV
          fi

      - name: Set up QEMU
        if: ${{ env.VERSION != '' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        if: ${{ env.VERSION != '' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to DockerHub
        if: ${{ env.VERSION != '' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Push images to Docker hub
        if: ${{ env.VERSION != '' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
        uses: docker/build-push-action@v5.1.0
        with:
          push: true
          platforms: linux/amd64, linux/arm64
          build-args: VERSION=${{ env.VERSION }}
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:${{ env.TAG }}

      - name: Upload to repository
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        if: ${{ env.VERSION != '' }}
        with:
          commit_message: Build beta to v${{ env.VERSION }} by Github Actions, ${{ env.DATE }}